config/routes.rb
Rails.application.routes.draw do
  
  resources :gemtips
  resources :cryptos
  resources :profiles
  resources :balances
  
  
  devise_for :users
  root 'home#index'
  get 'home/prices'

  get '/tipcheck', :controller=>'gemtips', :action=>'showtip'
  post '/validate', :controller=>'gemtips', :action=>'checktip'
  
  post "/home/prices" => 'home/prices'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
end

app/models/gemtip.rb
class Gemtip < ApplicationRecord
end

app/controllers/gemtips_controller.rb
class GemtipsController < ApplicationController
  before_action :set_gemtip, only: %i[ show edit update destroy ]

  # GET /gemtips or /gemtips.json
  def index
    @gemtips = Gemtip.all
  end

  # GET /gemtips/1 or /gemtips/1.json
  def show
  end

  # GET /gemtips/new
  def new
    @gemtip = Gemtip.new
  end

  # GET /gemtips/1/edit
  def edit
  end

  # POST /gemtips or /gemtips.json
  def create
    @gemtip = Gemtip.new(gemtip_params)

    respond_to do |format|
      if @gemtip.save
        format.html { redirect_to @gemtip, notice: "Gemtip was successfully created." }
        format.json { render :show, status: :created, location: @gemtip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gemtip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gemtips/1 or /gemtips/1.json
  def update
    respond_to do |format|
      if @gemtip.update(gemtip_params)
        format.html { redirect_to @gemtip, notice: "Gemtip was successfully updated." }
        format.json { render :show, status: :ok, location: @gemtip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gemtip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gemtips/1 or /gemtips/1.json
  def destroy
    @gemtip.destroy
    respond_to do |format|
      format.html { redirect_to gemtips_url, notice: "Gemtip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def checktip
      @num = params[:search_string]
      @result = Saytip.runcheck(@num.to_i)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gemtip
      @gemtip = Gemtip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gemtip_params
      params.require(:gemtip).permit(:tipnumb)
    end
    
    
    
    
end

app/helpers/gemtips_helper.rb
module GemtipsHelper
end

app/views/gemtips/_form.html.erb
<%= form_with(model: gemtip, local: true) do |form| %>
  <% if gemtip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gemtip.errors.count, "error") %> prohibited this gemtip from being saved:</h2>

      <ul>
      <% gemtip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipnumb %>
    <%= form.number_field :tipnumb, id: :gemtip_tipnumb %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gemtips/checktip.html.erb
The tip is<br>
Tip <%= @num %> is <%= @result %>

app/views/gemtips/edit.html.erb
<h1>Editing Gemtip</h1>

<%= render 'form', gemtip: @gemtip %>

<%= link_to 'Show', @gemtip %> |
<%= link_to 'Back', gemtips_path %>

app/views/gemtips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gemtips</h1>

<table>
  <thead>
    <tr>
      <th>Tipnumb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gemtips.each do |gemtip| %>
      <tr>
        <td><%= gemtip.tipnumb %></td>
        <td><%= link_to 'Show', gemtip %></td>
        <td><%= link_to 'Edit', edit_gemtip_path(gemtip) %></td>
        <td><%= link_to 'Destroy', gemtip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gemtip', new_gemtip_path %>

app/views/gemtips/new.html.erb
<h1>New Gemtip</h1>

<%= render 'form', gemtip: @gemtip %>

<%= link_to 'Back', gemtips_path %>

app/views/gemtips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipnumb:</strong>
  <%= @gemtip.tipnumb %>
</p>

<%= link_to 'Edit', edit_gemtip_path(@gemtip) %> |
<%= link_to 'Back', gemtips_path %>

app/views/gemtips/showtip.html.erb
<h1>Enter the Tip you want to see!</h1>
<%= form_tag "/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Search" %>
<% end %>