config/routes.rb
Rails.application.routes.draw do
  
  resources :gemtips
  resources :cryptos
  resources :profiles
  resources :balances
  
  
  devise_for :users
  root 'home#index'
  get 'home/prices'

  get '/tipcheck', :controller=>'gemtips', :action=>'showtip'
  post '/validate', :controller=>'gemtips', :action=>'checktip'
  
  post "/home/prices" => 'home/prices'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_many :balances
    
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :country, presence: true
    validates :number, presence: true
    validates :user_id, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end
  
  def signedinuserprofile 
    profile = Profile.find_by_user_id(current_user.id) 
    if profile.nil? 
      redirect_to "/profiles/new"
    else
      @profile = Profile.find_by_user_id(current_user.id) 
      redirect_to "/profiles/#{@profile.id}" 
    end
  end


  # GET /profiles/1 or /profiles/1.json
  def show
    @profile = Profile.find(params[:id]).decorate
  end

  # GET /profiles/new
  def new
    @profile = Profile.new 
    @profile.user_id = current_user.id
    
    respond_to do |format|
      format.html 
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :country, :number)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %><br />
    <%= form.text_field :first_name, id: :profile_first_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name %><br />
    <%= form.text_field :last_name, id: :profile_last_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :country %><br />
    <%= form.text_field :country, id: :profile_country, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :number %><br />
    <%= form.number_field :number, id: :profile_number, class: "form-control" %>
  </div>
  
  <br />
  <div class="actions">
    <%= form.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', @profile %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Country</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.country %></td>
        <td><%= profile.number %></td>
        <% if current_user && current_user.admin? %>
          <td><%= link_to 'Show', profile %></td>
          <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
          <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h2>Create profile for account: <%= @profile.user.username %> </h2>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
  <h1> <%= @profile.user.username %> Profile Page</h1>
  
  <br/>
  <h3>Welcome <%= @profile.full_name %> to you're profile page</h3>
  <h3>A username of "<%= @profile.user.username %>" has been generated for you!</h3>

  


  <br/>
  
<div class="jumbotron">
  <p>
    <strong>First name:</strong>
    <%= @profile.first_name %>
  </p>
  
  <p>
    <strong>Last name:</strong>
    <%= @profile.last_name %>
  </p>
  
  <p>
    <strong>Country:</strong>
    <%= @profile.country %>
  </p>
  
  <p>
    <strong>Number:</strong>
    <%= @profile.number %>
  </p>
</div>


<%= link_to 'Edit', edit_profile_path(@profile), :class => "btn btn-warning" %> |
<%= link_to 'Delete', profile_path(@profile), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>