config/routes.rb
Rails.application.routes.draw do
  
  resources :gemtips
  resources :cryptos
  resources :profiles
  resources :balances
  
  
  devise_for :users
  root 'home#index'
  get 'home/prices'

  get '/tipcheck', :controller=>'gemtips', :action=>'showtip'
  post '/validate', :controller=>'gemtips', :action=>'checktip'
  
  post "/home/prices" => 'home/prices'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    #reading from the news API for news articles
    @url = 'https://min-api.cryptocompare.com/data/v2/news/?lang=EN'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @news = JSON.parse(@response)
    
    #reading crypto coin vaule data
    @coin_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,LTC,ZRX,OMG,XLM,BCH&tsyms=EUR'
    @coin_uri = URI(@coin_url)
    @coin_response = Net::HTTP.get(@coin_uri)
    @coin_price = JSON.parse(@coin_response)
    
    
    @cryptos = Crypto.all
    
    @curr_url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=100&CMC_PRO_API_KEY=ae35850b-71ac-42cc-8804-fc3c37932a1d'
    @curr_uri = URI(@curr_url)
    @curr_response = Net::HTTP.get(@curr_uri)
    @extra_coin_price = JSON.parse(@curr_response)
    
    @coins_arr = ["BTC", "ADA", "OMG", "XRP", "STEEM", "ETH" ] 
    
    
  end
  
  def prices
    require 'net/http'
    require 'json'
    
    @coinsearch = params[:findcoin].to_s.upcase
    if @coinsearch.present?
      #needed for search bar
      @searchcoin_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=' + @coinsearch + '&tsyms=EUR'
      @searchcoin_uri = URI(@searchcoin_url)
      @searchcoin_response = Net::HTTP.get(@searchcoin_uri)
      @searchcoin_result = JSON.parse(@searchcoin_response)
      
    end
  end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Crypto Hub", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to "Get Prices", home_prices_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to "Purchases", balances_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to "Portfolio", cryptos_path, class: 'nav-link' %>
      </li>
    </ul>
    
    <% if current_user %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary my-2 my-sm-0' %>
      <% if current_user.profile == nil %> 
        <%= link_to 'Create Profile', new_profile_path, class: 'btn btn-outline-primary my-2 my-sm-0' %>
      <% else %>
        <%= link_to 'Profile', current_user.profile, class: 'btn btn-outline-primary my-2 my-sm-0' %>
      <% end %>
    <% else %>
      <%= link_to 'Signup', new_user_registration_path, class: 'btn btn-outline-secondary my-2 my-sm-0'%>
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-secondary my-2 my-sm-0' %>
    <% end %>
    <%= form_tag home_prices_path, :method => 'POST', class: "form-inline my-2 my-lg-0" do %>
    <%= text_field_tag 'findcoin', nil, placeholder: 'Enter Crypto Tag', class: 'form-control mr-sm-2' %>
    <%= submit_tag 'Search', class: 'btn btn-outline-secondary my-2 my-sm-0' %>
    <% end %>
    
  </div>
</nav>

app/views/home/index.html.erb
<table class="table table-striped table-bordered table-hover caption-top">
  <caption>Coin value table</caption>
  <thead class="thead-dark">
    <tr>
       <th scope="col">Name</th>
       <th scope="col">Price</th>
       <th scope="col">24h High</th>
       <th scope="col">24h Low</th>
       <th scope="col">Market Cap</th>
    </tr>
    </thead>
    <tbody>
        <% @coin_price["DISPLAY"].each do |key, value| %>
    <tr>
        <td><%= key %></td>
        <td><%= value["EUR"]["PRICE"] %></td>
        <td><%= value["EUR"]["HIGHDAY"] %></td>
        <td><%= value["EUR"]["LOWDAY"] %></td>
        <td><%= value["EUR"]["MKTCAP"] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br/>

<br/>
<div class="container-fluid">
 <div class="row">
  
  <% for i in @news["Data"]  %>
  
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
       
        <img src="<%= i["imageurl"] %>" class="card-img-top" alt="<%= i["source"] %>">
        <div class="card-body">
          <h5 class="card-title"><%= i["title"] %></h5>
          <p class="card-text"><%= i["body"] %></p>
          <a href="<%= i["url"] %>" class="btn btn-secondary">See Full</a>
        </div>
        
      </div>
      <br/>
    </div>
   <% end %>
 </div>
</div>

app/views/home/prices.html.erb
<% if @coinsearch.present? %>

  <% if @searchcoin_result["Response"] %>
    <h2>Crypto symbol <%= @coinsearch %> does not exist. Check and try again!</h2>
  <% else %>
  
    <% @searchcoin_result["DISPLAY"].each do |keyone, valueone| %>
      <div class="jumbotron">
        <h1 class="display-4"><%= keyone %></h1>
          Price: <%= valueone["EUR"]["PRICE"] %><br/>
          Open 24h price: <%= valueone["EUR"]["OPEN24HOUR"] %> <br/>
          24h High: <%= valueone["EUR"]["HIGHDAY"] %><br/>
          24h Low: <%= valueone["EUR"]["LOWDAY"] %><br/>
          Day change in price: <%= valueone["EUR"]["CHANGE24HOUR"] %><br/>
          Market Cap: <%= valueone["EUR"]["MKTCAP"] %><br/>
      </div>
    <% end %>
    
  <% end %>
<% else %>
    <h2>Enter a Coin in the search to view results</h2>
<% end %>