config/routes.rb
Rails.application.routes.draw do
  
  resources :gemtips
  resources :cryptos
  resources :profiles
  resources :balances
  
  
  devise_for :users
  root 'home#index'
  get 'home/prices'

  get '/tipcheck', :controller=>'gemtips', :action=>'showtip'
  post '/validate', :controller=>'gemtips', :action=>'checktip'
  
  post "/home/prices" => 'home/prices'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :user
  has_one :profile
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  before_action :set_balance, only: %i[ show edit update destroy ]
  #To make it so a user does not have to be signed in to view posts
  before_action :authenticate_user!, except: [:show, :index]
  # GET /balances or /balances.json
  def index
    @balances = Balance.all
  end

  # GET /balances/1 or /balances/1.json
  def show
  end

  # GET /balances/new
  def new
    @balance = Balance.new
  end

  # GET /balances/1/edit
  def edit
  end

  # POST /balances or /balances.json
  def create
    @balance = Balance.new(balance_params)
    @balance.user = current_user
    respond_to do |format|
      if @balance.save
        format.html { redirect_to @balance, notice: "Balance was successfully created." }
        format.json { render :show, status: :created, location: @balance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balances/1 or /balances/1.json
  def update
    respond_to do |format|
      if @balance.update(balance_params)
        format.html { redirect_to @balance, notice: "Balance was successfully updated." }
        format.json { render :show, status: :ok, location: @balance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @balance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balances/1 or /balances/1.json
  def destroy
    @balance.destroy
    respond_to do |format|
      format.html { redirect_to balances_url, notice: "Balance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_balance
      @balance = Balance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def balance_params
      params.require(:balance).permit(:balance)
    end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.erb
<%= form_with(model: balance, local: true) do |form| %>
  <% if balance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(balance.errors.count, "error") %> prohibited this balance from being saved:</h2>

      <ul>
      <% balance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :balance %>
    <%= form.number_field :balance, id: :balance_balance, class: "form-control" %>
  </div>
  <br/>

  <div class="actions">
    <%= form.submit "Add", class: "btn btn-primary" %>
  </div>
  <br/>
<% end %>

app/views/balances/edit.html.erb
<h1>Editing Balance</h1>

<%= render 'form', balance: @balance %>

<%= link_to 'Show', @balance, :class =>"btn btn-info add-new" %> |
<%= link_to 'Back', balances_path, :class =>"btn btn-info add-new" %>

app/views/balances/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
        <div>
            <div>
                <div class="row">
                    <div class="col-sm-10"><h2><b>Crypto purchases</b></h2></div>
                    <div class="col-sm-2">
                        <%= link_to 'Add purchase ', new_balance_path, :class => "btn btn-info add-new"  %>
                    </div>
                </div>
            </div>
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>User ID</th>
                        <th>Name</th>
                        <th>Spent</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                  <% @balances.each do |balance| %>
                    <tr>
                        <td><%= balance.user.id %></td>
                        <td><%= balance.user.username %></td>
                        <td>€<%= balance.balance %></td>
                        <td>
							<%= link_to 'Show', balance, :class => "btn btn-primary btn-sm" %>
							<% if current_user && current_user.admin? %>
                                <%= link_to 'Edit', edit_balance_path(balance), :class => "btn btn-warning btn-sm" %>
                                <%= link_to 'Remove', balance, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %>
                            <% end %>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
    </div>         

app/views/balances/new.html.erb
<h1>Enter amount spent to be posted on the board</h1>

<%= render 'form', balance: @balance %>

<%= link_to 'Back', balances_path, :class =>"btn btn-info add-new" %>

app/views/balances/show.html.erb
<p>
  <strong>Amount spent:</strong>
  $<%= @balance.balance %>
</p>

<p>
  <strong>User:</strong>
  <%= @balance.user.username %>
</p>

<%= link_to 'Back', balances_path, :class =>"btn btn-info add-new" %>